export const htmlElement: Record<string, HTMLElement | null> = {
  body: document.querySelector('body'),
  errorModal: document.querySelector('.error-modal'),
  errorModalContent: document.querySelector('.error-modal__content'),
  themeContainer: document.querySelector('.header__theme-cont'),
  themeLight: document.querySelector('.theme--light'),
  themeDark: document.querySelector('.theme--dark'),
  navbarForm: document.querySelector('.navbar__form'),
  backBtn: document.querySelector('.backbtn'),
  searchBoxId: document.querySelector('#js-countrySearchbox'),
  searchBoxClass: document.querySelector('.searchbox'),
  searchboxCont: document.querySelector('.searchbox__cont'),
  searchboxCloseIcon: document.querySelector('.searchbox__icon--close'),
  searchboxSubmit: document.querySelector('.searchbox__submit'),
  searchboxListCont: document.querySelector('.searchbox__list-cont'),
  searchboxList: document.querySelector('.searchbox__list'),
  dropdownbox: document.querySelector('.dropdown-box'),
  dropdownboxSelected: document.querySelector('.dropdown-box__selected'),
  dropdownboxListCont: document.querySelector('.dropdown-box__list-cont'),
  dropdownboxIcon: document.querySelector('.dropdown-box__icon'),
  main: document.querySelector('.main'),
  mainCont: document.querySelector('.main__cont'),
  country: document.querySelector('.country'),
  countryDetailModal: document.querySelector('.country-detail'),
  countryDetailModalCloseBtn: document.querySelector('.country-detail__cross'),
};

export const countryDetailSelector: Record<string, HTMLElement | null> = {
  heading: document.querySelector('.country-detail__heading'),
  flagImg: document.querySelector('.country-detail__img'),
  nativeName: document.querySelector('.js-country-native-name'),
  population: document.querySelector('.js-country-population'),
  region: document.querySelector('.js-country-region'),
  subRegion: document.querySelector('.js-country-sub-region'),
  capital: document.querySelector('.js-country-capital'),
  topLevelDomain: document.querySelector('.js-country-top-level-domain'),
  currencies: document.querySelector('.js-country-currencies'),
  languages: document.querySelector('.js-country-languages'),
  borderCountries: document.querySelector('.country-detail__border-countries'),
  noBorderCountriesText: document.querySelector(
      '.country-detail__border--none-text',
  ),
  borderCountriesList: document.querySelector(
      '.country-detail__border-countries__list',
  ),
};
